const dictionaryId = {
    id00001_seguridad: "La importancia de la seguridad en los procesos",  
    id00001_residuos: "Manejo de residuos",  
    id00001_vigilar: "5 Claves para vigilar la seguridad",  
    id00002_cartel: "Cartel",  
    id00002_redes: "Redes sociales",  
    id00002_video: "Video",  
    id00002_podcast: "Podcast",  
    id00002_pagina: "Página web",  
    id00002_articulo: "Artículo promocional",  
    id00003_seguridad_depende: "La seguridad depende de ti",  
    id00003_permiso_trabajo: "Un permiso de trabajo es un seguro de vida",  
    id00003_trabajo_seguro: "Trabaja seguro, Trabaja con EPP",  
    id00004_uso_epp: "Uso del EPP",  
    id00004_manejo_residuos: "Manejo de residuos",  
    id00004_procedimientos: "Procedimientos seguros",  
    id00004_ninguno: "Ninguno de los anteriores",  
    id00005_muy_frecuente: "Muy frecuente",  
    id00005_nada_frecuente: "Nada frecuente",  
    id00005_nada: "No he visto nada",  
    id00006_inefectiva: "Inefectiva",  
    id00006_poco_efectiva: "Poco efectiva",  
    id00006_efectiva: "Efectiva",  
    id00006_muy_efectiva: "Muy efectiva",  
    id00006_altamente_efectiva: "Altamente efectiva", 
    //encuesta 2
    id00007_no_informativa: "No informativa",
    id00007_poco_informativa : "Poco informativa",
    id00007_informativa: "Informativa",
    id00007_muy_informativa: "Muy informativa",
    id00007_altamente_informativa: "Altamente informativa",
    id00008_si_mejorado: "Sí, he mejorado mis prácticas de manejo de residuos",
    id00008_si_comenzado: "Sí, he comenzado a reciclar o a reducir mi producción de residuos",
    id00008_no_siguen: "No, mis hábitos de manejo de residuos siguen siendo los mismos",
    id00008_no_estoy_seguro: "No estoy seguro",
    id00009_si_impacto_positivo: "Sí",
    id00009_no_impacto_positivo: "No",
    id00009_no_seguro_impacto: "No estoy seguro",
      
  }
  
  module.exports = dictionaryId